# Generated by Django 4.0.1 on 2022-04-23 05:47

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_my_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='my_field',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('0', 'IT'), ('1', 'Accounting'), ('2', 'Sales'), ('3', 'F&B'), ('4', 'SPA')], max_length=9),
        ),
    ]
