# Generated by Django 4.0.1 on 2022-04-23 09:39

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_account_my_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='my_field',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'IT'), (2, 'Accounting'), (3, 'F&B'), (4, 'SPA')], max_length=7),
        ),
    ]
