# Generated by Django 4.0.1 on 2022-04-23 13:11

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_account_my_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='my_field',
            new_name='allowed_departments',
        ),
        migrations.AddField(
            model_name='account',
            name='access',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Initiator'), (2, 'Purchasing'), (3, 'Accounting Control'), (4, 'DOF'), (5, 'GM')], default=False, max_length=9),
            preserve_default=False,
        ),
    ]
