# Generated by Django 4.0.1 on 2022-04-23 13:12

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_my_field_account_allowed_departments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='accesses',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Initiator'), (2, 'Purchasing'), (3, 'Accounting Control'), (4, 'DOF'), (5, 'GM')], default=False, max_length=9),
            preserve_default=False,
        ),
    ]
