# Generated by Django 4.0.1 on 2022-04-23 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_account_accesses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='access',
        ),
        migrations.RemoveField(
            model_name='account',
            name='accesses',
        ),
    ]
