# Generated by Django 4.0.1 on 2022-04-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_account_access'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='access',
        ),
        migrations.AddField(
            model_name='account',
            name='dof_rights',
            field=models.BooleanField(default=False, verbose_name='DOF Right'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='gm_rights',
            field=models.BooleanField(default=False, verbose_name='GM Rights'),
            preserve_default=False,
        ),
    ]
