# Generated by Django 4.0.4 on 2022-05-04 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Contract Type')),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Currency')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Department Name')),
                ('count', models.IntegerField(verbose_name='Count')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Payment Terms')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Contract Status')),
            ],
        ),
        migrations.CreateModel(
            name='TerminationTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Termination Terms')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('vendor_code', models.CharField(max_length=10, verbose_name='Vendor Code')),
                ('contract_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Contract ID')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('hod_comments', models.CharField(blank=True, max_length=200, null=True, verbose_name='HOD Comments')),
                ('account_number', models.IntegerField(blank=True, null=True, verbose_name='Acccount Number')),
                ('approval_status', models.IntegerField(default=0, verbose_name='Approval Status')),
                ('contract_value', models.IntegerField(verbose_name='Contract Value')),
                ('vendor_email', models.EmailField(max_length=80, verbose_name='Vendor Email')),
                ('vendor_phone', models.CharField(max_length=40, verbose_name='Vendor Phone')),
                ('vendor_director', models.CharField(max_length=40, verbose_name='Vendor Director')),
                ('vendor_name', models.CharField(max_length=40, verbose_name='Vendor Name')),
                ('vendor_voen', models.IntegerField(blank=True, default=False, null=True, verbose_name='Vendor VÖEN')),
                ('vendor_address', models.CharField(blank=True, default=False, max_length=40, null=True, verbose_name='Vendor Address')),
                ('bank_name', models.CharField(blank=True, default=False, max_length=20, null=True, verbose_name='Bank Name')),
                ('bank_voen', models.CharField(blank=True, default=False, max_length=20, null=True, verbose_name='Bank VOEN')),
                ('bank_code', models.CharField(blank=True, default=False, max_length=20, null=True, verbose_name='Bank Code')),
                ('bank_swift', models.CharField(blank=True, default=False, max_length=30, null=True, verbose_name='Bank SWIFT')),
                ('bank_m_h', models.CharField(blank=True, default=False, max_length=30, null=True, verbose_name='Bank Müxbir Hesab')),
                ('bank_h_h', models.CharField(blank=True, default=False, max_length=30, null=True, verbose_name='Bank Hesablaşma Hesabı')),
                ('contract_exported_link', models.CharField(max_length=300, null=True, verbose_name='Link')),
                ('creator_edit', models.BooleanField(default=True, verbose_name='Initiator can edit')),
                ('contract_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Purchase.contracttype')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Purchase.currency')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Purchase.department')),
                ('payment_terms', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Purchase.paymentterms')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Purchase.status')),
                ('termination_terms', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Purchase.terminationterms')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
