# Generated by Django 4.0.4 on 2022-05-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_exported_link',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Link'),
        ),
    ]
