# Generated by Django 4.0.4 on 2022-05-06 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0002_alter_contract_contract_exported_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='reject_comment',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Rejection Comment'),
        ),
    ]
