# Generated by Django 3.2.16 on 2022-12-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0003_contract_reject_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='percentage',
            field=models.IntegerField(default=True, verbose_name='Contract Percentage'),
            preserve_default=False,
        ),
    ]
